version: '3'
services:
  service:
    container_name: spring-kafka
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - db:db.spring-kafka.com
      - kafka:kafka
    environment:
      SPRING_PROFILES_ACTIVE: development
    depends_on:
      - db
      - zookeeper
      - kafka
  db:
    container_name: db
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: spring-kafka


  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    expose:
      - "2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    hostname: kafka
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: LISTENER_BOB://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: test:1:1