version: '3'
services:
  service:
    container_name: spring-kafka
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - db:db.spring-kafka.com
    environment:
      SPRING_PROFILES_ACTIVE: development
    depends_on:
      - db
  db:
    container_name: db
    image: mysql/mysql-server
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: spring-kafka


  zookeeper:
    image: wurstmeister/zookeeper:latest
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181